// TypeScript interfaces for Tourist Safety API
// Use these types in your React/Angular/Vue applications

export interface Location {
  coordinates: [number, number]; // [longitude, latitude]
  address: string;
}

export interface EmergencyContact {
  name: string;
  phone: string;
  relation: string;
}

export interface UserPreferences {
  language: string;
  notifications: boolean;
  locationSharing: boolean;
}

export interface User {
  _id: string;
  email: string;
  name: string;
  role: 'tourist' | 'authority';
  phone: string;
  profilePicture: string;
  location: Location;
  createdAt: string;
  updatedAt: string;
}

export interface Tourist extends User {
  role: 'tourist';
  safetyScore: number;
  loyaltyPoints: number;
  digitalId: string;
  emergencyContacts: EmergencyContact[];
  preferences: UserPreferences;
}

export interface Authority extends User {
  role: 'authority';
  badgeNumber: string;
  department: string;
  jurisdiction: string;
}

export interface ConfirmationStep {
  question: string;
  answer: string;
  timestamp: string;
}

export interface AlertResponse {
  responderId: string;
  responderName: string;
  estimatedArrival: string;
  status: 'notified' | 'en_route' | 'arrived' | 'completed';
  message: string;
  timestamp: string;
}

export interface SOSAlert {
  _id: string;
  userId: string;
  type: 'emergency' | 'medical' | 'theft' | 'lost';
  description: string;
  location: Location;
  status: 'active' | 'acknowledged' | 'resolved' | 'cancelled';
  priority: 'low' | 'medium' | 'high' | 'critical';
  confirmationSteps: ConfirmationStep[];
  responses: AlertResponse[];
  mediaUrls: string[];
  isAnonymous: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Evidence {
  type: 'photo' | 'video' | 'document' | 'audio';
  url: string;
  description: string;
  uploadedAt: string;
}

export interface InvestigationUpdate {
  date: string;
  update: string;
  officer: string;
}

export interface Investigation {
  updates: InvestigationUpdate[];
  currentStatus: string;
}

export interface OfficerAssigned {
  id: string;
  name: string;
  badgeNumber: string;
  contactNumber: string;
}

export interface EFIR {
  _id: string;
  firNumber: string;
  complainantId: string;
  complainantName: string;
  incidentType: 'theft' | 'fraud' | 'assault' | 'harassment' | 'other';
  description: string;
  location: Location;
  incidentDate: string;
  status: 'registered' | 'under_investigation' | 'closed';
  officerAssigned: OfficerAssigned;
  evidence: Evidence[];
  investigation: Investigation;
  priority: 'low' | 'medium' | 'high';
  autoGenerated: boolean;
  relatedSOSAlert?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ChatbotResponse {
  message: string;
  suggestions: string[];
  quickActions?: Array<{
    action: string;
    label: string;
  }>;
}

export interface ChatMessage {
  userMessage: string;
  botResponse: ChatbotResponse;
  timestamp: string;
}

export interface Translation {
  originalText: string;
  translatedText: string;
  sourceLanguage: string;
  targetLanguage: string;
  confidence: number;
}

export interface DashboardStats {
  overview: {
    totalAlerts: number;
    activeAlerts: number;
    resolvedAlerts: number;
    totalTourists: number;
    safetyScore: number;
  };
  todaysStats: {
    newAlerts: number;
    newFIRs: number;
    responseTime: string;
    touristsHelped: number;
  };
  recentAlerts: SOSAlert[];
  alertsByType: Record<string, number>;
  alertsByHour: Array<{ hour: number; count: number }>;
  touristClusters: Array<{
    location: { lat: number; lng: number };
    count: number;
    area: string;
  }>;
}

export interface ApiResponse<T> {
  success: boolean;
  data: T;
  message: string;
  total?: number;
}

export interface AuthResponse {
  user: Tourist | Authority;
  token: string;
  refreshToken: string;
  expiresIn: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface RegisterRequest {
  email: string;
  password: string;
  name: string;
  role: 'tourist' | 'authority';
  phone: string;
}

export interface CreateSOSRequest {
  type: 'emergency' | 'medical' | 'theft' | 'lost';
  description: string;
  location: {
    coordinates: [number, number];
    address: string;
  };
  isAnonymous?: boolean;
}

export interface CreateEFIRRequest {
  incidentType: 'theft' | 'fraud' | 'assault' | 'harassment' | 'other';
  description: string;
  incidentDate: string;
  location: {
    coordinates: [number, number];
    address: string;
  };
  suspects?: any[];
  witnesses?: any[];
}

export interface ChatRequest {
  message: string;
  context?: string;
}

export interface TranslationRequest {
  text: string;
  targetLanguage: string;
  sourceLanguage?: string;
}
