const express = require('express');
const { body, validationResult } = require('express-validator');
const EFIR = require('../models/EFIR');
const SOSAlert = require('../models/SOSAlert');
const User = require('../models/User');
const { auth } = require('../middleware/auth');
const router = express.Router();

/**
 * @swagger
 * components:
 *   schemas:
 *     EFIR:
 *       type: object
 *       required:
 *         - incidentType
 *         - incidentLocation
 *         - incidentTime
 *         - description
 *         - complainant
 *       properties:
 *         incidentType:
 *           type: string
 *           enum: [missing_person, theft, assault, harassment, fraud, accident, medical_emergency, natural_disaster, other]
 *         incidentLocation:
 *           type: object
 *           properties:
 *             coordinates:
 *               type: array
 *               items:
 *                 type: number
 */

/**
 * @swagger
 * /api/efir/create:
 *   post:
 *     summary: Create E-FIR
 *     tags: [E-FIR]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/EFIR'
 *     responses:
 *       201:
 *         description: E-FIR created successfully
 *       400:
 *         description: Bad request
 */
router.post('/create', auth, [
  body('incidentType').isIn([
    'missing_person', 'theft', 'assault', 'harassment', 
    'fraud', 'accident', 'medical_emergency', 'natural_disaster', 'other'
  ]),
  body('incidentLocation.coordinates').isArray().custom((value) => {
    if (value.length !== 2 || !value.every(coord => typeof coord === 'number')) {
      throw new Error('Coordinates must be an array of two numbers [longitude, latitude]');
    }
    return true;
  }),
  body('incidentTime').isISO8601().toDate(),
  body('description').isLength({ min: 20 }),
  body('complainant.name').trim().isLength({ min: 1 })
], async (req, res) => {
  try {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({
        success: false,
        message: 'Validation errors',
        errors: errors.array()
      });
    }

    const {
      relatedAlertId,
      incidentType,
      incidentLocation,
      incidentTime,
      description,
      complainant,
      victim,
      circumstances,
      suspectDescription,
      witnessDetails,
      evidence
    } = req.body;

    // Generate unique FIR number
    const firNumber = await EFIR.generateFIRNumber();

    // Get user details for complainant if not provided
    const user = await User.findOne({ userId: req.user.userId });
    
    const efirData = {
      firNumber,
      relatedAlertId,
      complainant: {
        userId: req.user.userId,
        name: complainant.name || `${user.firstName} ${user.lastName}`,
        contact: {
          phone: complainant.contact?.phone || user.phoneNumber,
          email: complainant.contact?.email || user.email
        },
        address: complainant.address,
        relationship: complainant.relationship || 'self'
      },
      incidentType,
      incidentLocation,
      incidentTime,
      description,
      circumstances,
      suspectDescription,
      witnessDetails: witnessDetails || [],
      evidence: evidence || [],
      victim: victim || {
        name: `${user.firstName} ${user.lastName}`,
        digitalId: user.userType === 'tourist' ? user.touristProfile?.digitalId : null
      }
    };

    // Set priority based on incident type
    if (['missing_person', 'assault', 'medical_emergency'].includes(incidentType)) {
      efirData.priority = 'urgent';
    } else if (['theft', 'harassment', 'fraud'].includes(incidentType)) {
      efirData.priority = 'high';
    } else {
      efirData.priority = 'medium';
    }

    // Check if auto-generated from SOS alert
    if (relatedAlertId) {
      const sosAlert = await SOSAlert.findOne({ alertId: relatedAlertId });
      if (sosAlert) {
        efirData.isAutoGenerated = true;
        efirData.generatedFrom = 'sos_alert';
        efirData.incidentLocation = sosAlert.location;
        
        // Auto-populate additional fields from SOS
        if (sosAlert.address) efirData.incidentAddress = sosAlert.address;
        if (sosAlert.description) efirData.circumstances = sosAlert.description;
      }
    }

    const efir = new EFIR(efirData);
    await efir.save();

    // Update related SOS alert status if exists
    if (relatedAlertId) {
      await SOSAlert.findOneAndUpdate(
        { alertId: relatedAlertId },
        { status: 'resolved' }
      );
    }

    res.status(201).json({
      success: true,
      message: 'E-FIR created successfully',
      data: {
        firNumber: efir.firNumber,
        status: efir.status,
        priority: efir.priority,
        incidentType: efir.incidentType,
        createdAt: efir.createdAt
      }
    });

  } catch (error) {
    console.error('E-FIR creation error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to create E-FIR',
      error: error.message
    });
  }
});

/**
 * @swagger
 * /api/efir/auto-generate/{alertId}:
 *   post:
 *     summary: Auto-generate E-FIR from SOS alert
 *     tags: [E-FIR]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: alertId
 *         required: true
 *         schema:
 *           type: string
 *     responses:
 *       201:
 *         description: E-FIR auto-generated successfully
 *       404:
 *         description: SOS alert not found
 */
router.post('/auto-generate/:alertId', auth, async (req, res) => {
  try {
    // Check if user is authority
    if (req.user.userType !== 'authority' && req.user.userType !== 'admin') {
      return res.status(403).json({
        success: false,
        message: 'Only authorities can auto-generate E-FIRs'
      });
    }

    const { alertId } = req.params;
    const sosAlert = await SOSAlert.findOne({ alertId });

    if (!sosAlert) {
      return res.status(404).json({
        success: false,
        message: 'SOS alert not found'
      });
    }

    // Check if E-FIR already exists for this alert
    const existingEFIR = await EFIR.findOne({ relatedAlertId: alertId });
    if (existingEFIR) {
      return res.status(400).json({
        success: false,
        message: 'E-FIR already exists for this SOS alert',
        data: { firNumber: existingEFIR.firNumber }
      });
    }

    const tourist = await User.findOne({ userId: sosAlert.userId });
    const authority = await User.findOne({ userId: req.user.userId });

    // Map SOS alert type to incident type
    const incidentTypeMapping = {
      'emergency': 'other',
      'medical': 'medical_emergency',
      'security': 'assault',
      'lost': 'missing_person',
      'accident': 'accident'
    };

    const firNumber = await EFIR.generateFIRNumber();

    const efir = new EFIR({
      firNumber,
      relatedAlertId: alertId,
      complainant: {
        userId: authority.userId,
        name: `${authority.firstName} ${authority.lastName}`,
        contact: {
          phone: authority.phoneNumber,
          email: authority.email
        },
        relationship: 'authority'
      },
      incidentType: incidentTypeMapping[sosAlert.alertType] || 'other',
      incidentLocation: sosAlert.location,
      incidentAddress: sosAlert.address,
      incidentTime: sosAlert.createdAt,
      description: sosAlert.description || `Auto-generated from SOS Alert ${alertId}`,
      circumstances: sosAlert.message,
      victim: {
        name: sosAlert.touristName,
        digitalId: tourist?.touristProfile?.digitalId,
        lastKnownLocation: sosAlert.location,
        lastSeenTime: sosAlert.createdAt
      },
      priority: sosAlert.priority === 'critical' ? 'urgent' : sosAlert.priority,
      isAutoGenerated: true,
      generatedFrom: 'sos_alert',
      status: 'submitted',
      assignedTo: {
        officerId: authority.userId,
        officerName: `${authority.firstName} ${authority.lastName}`,
        department: authority.authorityProfile?.department || 'Tourism Police',
        assignedDate: new Date()
      }
    });

    await efir.save();

    // Update SOS alert status
    sosAlert.status = 'resolved';
    await sosAlert.save();

    res.status(201).json({
      success: true,
      message: 'E-FIR auto-generated successfully',
      data: {
        firNumber: efir.firNumber,
        relatedAlertId: alertId,
        status: efir.status,
        assignedTo: efir.assignedTo
      }
    });

  } catch (error) {
    console.error('E-FIR auto-generation error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to auto-generate E-FIR',
      error: error.message
    });
  }
});

/**
 * @swagger
 * /api/efir/update/{firNumber}:
 *   put:
 *     summary: Update E-FIR investigation
 *     tags: [E-FIR]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: firNumber
 *         required: true
 *         schema:
 *           type: string
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               description:
 *                 type: string
 *               actionTaken:
 *                 type: string
 *               nextSteps:
 *                 type: string
 *               status:
 *                 type: string
 *     responses:
 *       200:
 *         description: E-FIR updated successfully
 *       404:
 *         description: E-FIR not found
 */
router.put('/update/:firNumber', auth, [
  body('description').trim().isLength({ min: 1 }),
  body('actionTaken').optional().trim(),
  body('nextSteps').optional().trim()
], async (req, res) => {
  try {
    // Check if user is authority
    if (req.user.userType !== 'authority' && req.user.userType !== 'admin') {
      return res.status(403).json({
        success: false,
        message: 'Only authorities can update E-FIRs'
      });
    }

    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({
        success: false,
        message: 'Validation errors',
        errors: errors.array()
      });
    }

    const { firNumber } = req.params;
    const { description, actionTaken, nextSteps, status } = req.body;

    const efir = await EFIR.findOne({ firNumber });
    if (!efir) {
      return res.status(404).json({
        success: false,
        message: 'E-FIR not found'
      });
    }

    const user = await User.findOne({ userId: req.user.userId });

    // Add investigation update
    efir.addInvestigationUpdate({
      updatedBy: `${user.firstName} ${user.lastName}`,
      description,
      actionTaken: actionTaken || '',
      nextSteps: nextSteps || ''
    });

    // Update status if provided
    if (status) {
      efir.status = status;
    }

    await efir.save();

    res.json({
      success: true,
      message: 'E-FIR updated successfully',
      data: {
        firNumber: efir.firNumber,
        status: efir.status,
        lastUpdate: efir.investigation.updates[efir.investigation.updates.length - 1]
      }
    });

  } catch (error) {
    console.error('E-FIR update error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to update E-FIR',
      error: error.message
    });
  }
});

/**
 * @swagger
 * /api/efir/list:
 *   get:
 *     summary: Get E-FIR list
 *     tags: [E-FIR]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: query
 *         name: status
 *         schema:
 *           type: string
 *       - in: query
 *         name: incidentType
 *         schema:
 *           type: string
 *       - in: query
 *         name: priority
 *         schema:
 *           type: string
 *       - in: query
 *         name: page
 *         schema:
 *           type: integer
 *       - in: query
 *         name: limit
 *         schema:
 *           type: integer
 *     responses:
 *       200:
 *         description: E-FIR list retrieved successfully
 */
router.get('/list', auth, async (req, res) => {
  try {
    const { status, incidentType, priority, page = 1, limit = 20 } = req.query;
    
    let query = {};
    
    // Filter by user for tourists, show assigned cases for authorities
    if (req.user.userType === 'tourist') {
      query['complainant.userId'] = req.user.userId;
    } else if (req.user.userType === 'authority') {
      query['assignedTo.officerId'] = req.user.userId;
    }
    
    if (status) query.status = status;
    if (incidentType) query.incidentType = incidentType;
    if (priority) query.priority = priority;

    const skip = (page - 1) * limit;
    
    const efirs = await EFIR.find(query)
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(parseInt(limit))
      .select('-investigation.updates -communications -evidence');

    const total = await EFIR.countDocuments(query);

    res.json({
      success: true,
      data: {
        efirs,
        pagination: {
          current: parseInt(page),
          total: Math.ceil(total / limit),
          count: efirs.length,
          totalRecords: total
        }
      }
    });

  } catch (error) {
    console.error('E-FIR list error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to retrieve E-FIR list',
      error: error.message
    });
  }
});

/**
 * @swagger
 * /api/efir/{firNumber}:
 *   get:
 *     summary: Get E-FIR details
 *     tags: [E-FIR]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: firNumber
 *         required: true
 *         schema:
 *           type: string
 *     responses:
 *       200:
 *         description: E-FIR details retrieved
 *       404:
 *         description: E-FIR not found
 */
router.get('/:firNumber', auth, async (req, res) => {
  try {
    const { firNumber } = req.params;
    
    let query = { firNumber };
    
    // Access control
    if (req.user.userType === 'tourist') {
      query['complainant.userId'] = req.user.userId;
    } else if (req.user.userType === 'authority') {
      // Authorities can see cases in their jurisdiction or assigned to them
      query.$or = [
        { 'assignedTo.officerId': req.user.userId },
        { jurisdiction: { $in: await getUserJurisdiction(req.user.userId) } }
      ];
    }

    const efir = await EFIR.findOne(query);

    if (!efir) {
      return res.status(404).json({
        success: false,
        message: 'E-FIR not found or access denied'
      });
    }

    res.json({
      success: true,
      data: { efir }
    });

  } catch (error) {
    console.error('E-FIR details error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to retrieve E-FIR details',
      error: error.message
    });
  }
});

// Helper function to get user jurisdiction
async function getUserJurisdiction(userId) {
  const user = await User.findOne({ userId });
  return user?.authorityProfile?.jurisdiction || [];
}

module.exports = router;
