const mongoose = require('mongoose');

const efirSchema = new mongoose.Schema({
  firNumber: {
    type: String,
    unique: true,
    required: true
  },
  
  // Related Alert
  relatedAlertId: {
    type: String,
    ref: 'SOSAlert'
  },
  
  // Complainant Information
  complainant: {
    userId: String,
    name: {
      type: String,
      required: true
    },
    contact: {
      phone: String,
      email: String
    },
    address: String,
    relationship: {
      type: String,
      enum: ['self', 'family', 'friend', 'witness', 'authority', 'other']
    }
  },
  
  // Incident Details
  incidentType: {
    type: String,
    enum: [
      'missing_person',
      'theft',
      'assault',
      'harassment',
      'fraud',
      'accident',
      'medical_emergency',
      'natural_disaster',
      'other'
    ],
    required: true
  },
  
  // Victim Information
  victim: {
    name: String,
    age: Number,
    gender: {
      type: String,
      enum: ['male', 'female', 'other', 'prefer_not_to_say']
    },
    nationality: String,
    passportNumber: String,
    digitalId: String,
    lastKnownLocation: {
      type: {
        type: String,
        enum: ['Point'],
        default: 'Point'
      },
      coordinates: [Number] // [longitude, latitude]
    },
    lastSeenTime: Date,
    physicalDescription: String,
    clothingDescription: String,
    medicalConditions: String
  },
  
  // Incident Location & Time
  incidentLocation: {
    type: {
      type: String,
      enum: ['Point'],
      default: 'Point'
    },
    coordinates: {
      type: [Number], // [longitude, latitude]
      required: true
    }
  },
  incidentAddress: String,
  incidentTime: {
    type: Date,
    required: true
  },
  reportedTime: {
    type: Date,
    default: Date.now
  },
  
  // Incident Description
  description: {
    type: String,
    required: true,
    minlength: 20
  },
  circumstances: String,
  suspectDescription: String,
  witnessDetails: [String],
  
  // Evidence
  evidence: [{
    type: {
      type: String,
      enum: ['document', 'photo', 'video', 'audio', 'physical_item']
    },
    description: String,
    fileUrl: String,
    collectedBy: String,
    collectionTime: Date
  }],
  
  // Status & Progress
  status: {
    type: String,
    enum: ['draft', 'submitted', 'under_investigation', 'resolved', 'closed', 'transferred'],
    default: 'draft'
  },
  priority: {
    type: String,
    enum: ['low', 'medium', 'high', 'urgent'],
    default: 'medium'
  },
  
  // Assignment
  assignedTo: {
    officerId: String,
    officerName: String,
    department: String,
    station: String,
    assignedDate: Date
  },
  
  // Investigation Progress
  investigation: {
    updates: [{
      updateId: String,
      timestamp: Date,
      updatedBy: String,
      description: String,
      actionTaken: String,
      nextSteps: String
    }],
    leads: [String],
    interviews: [{
      personName: String,
      role: String,
      date: Date,
      summary: String
    }],
    forensics: [{
      evidenceId: String,
      analysisType: String,
      results: String,
      date: Date
    }]
  },
  
  // Communication Log
  communications: [{
    timestamp: Date,
    type: {
      type: String,
      enum: ['phone_call', 'email', 'sms', 'meeting', 'video_call']
    },
    participants: [String],
    summary: String,
    followUpRequired: Boolean
  }],
  
  // Resolution
  resolution: {
    resolvedDate: Date,
    outcome: {
      type: String,
      enum: ['resolved', 'case_closed', 'referred_to_court', 'insufficient_evidence', 'withdrawn']
    },
    summary: String,
    actionsTaken: [String],
    compensation: {
      amount: Number,
      currency: String,
      status: String
    }
  },
  
  // Administrative
  jurisdiction: String,
  policeStation: String,
  caseOfficer: String,
  supervisingOfficer: String,
  
  // Auto-generated fields
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  generatedFrom: {
    type: String,
    enum: ['sos_alert', 'manual_entry', 'third_party_report']
  },
  
  // Legal
  legalStatus: {
    type: String,
    enum: ['pending', 'court_case_filed', 'under_trial', 'verdict_given'],
    default: 'pending'
  },
  courtCaseNumber: String
  
}, {
  timestamps: true
});

// Indexes
efirSchema.index({ firNumber: 1 });
efirSchema.index({ 'complainant.userId': 1 });
efirSchema.index({ relatedAlertId: 1 });
efirSchema.index({ status: 1 });
efirSchema.index({ incidentType: 1 });
efirSchema.index({ incidentLocation: '2dsphere' });
efirSchema.index({ 'victim.lastKnownLocation': '2dsphere' });
efirSchema.index({ incidentTime: -1 });
efirSchema.index({ priority: 1 });

// Virtual for case age
efirSchema.virtual('caseAge').get(function() {
  return Math.floor((Date.now() - this.createdAt) / (1000 * 60 * 60 * 24)); // days
});

// Method to generate FIR number
efirSchema.statics.generateFIRNumber = async function() {
  const year = new Date().getFullYear();
  const count = await this.countDocuments({
    createdAt: {
      $gte: new Date(year, 0, 1),
      $lt: new Date(year + 1, 0, 1)
    }
  });
  return `FIR${year}${String(count + 1).padStart(6, '0')}`;
};

// Method to update investigation
efirSchema.methods.addInvestigationUpdate = function(updateData) {
  this.investigation.updates.push({
    updateId: `UPD${Date.now()}`,
    timestamp: new Date(),
    ...updateData
  });
  
  // Auto-update status based on update type
  if (updateData.actionTaken && updateData.actionTaken.includes('resolved')) {
    this.status = 'resolved';
  }
};

// Method to assign case
efirSchema.methods.assignCase = function(officerData) {
  this.assignedTo = {
    ...officerData,
    assignedDate: new Date()
  };
  this.status = 'under_investigation';
};

module.exports = mongoose.model('EFIR', efirSchema);
